### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by btd1337** [naaando/wingpanel-indicator-pomodoro#4]
How to uninstall this?

![screenshot from 2018-03-10 02 48 09](https://user-images.githubusercontent.com/11943860/37238823-897f7d4a-240d-11e8-840b-1f5f41f9ab8a.jpeg)

**Comment by naaando** [comment]
Run install first to overwrite current installation and uninstall
or delete manually /usr/lib/x86_64-linux-gnu/wingpanel/libpomodoro.so

I'll upload and add .deb packages as the recommend source for installation later.

**Comment by robertsanseries** [comment]
@btd1337 Nesse caso seu, você está apenas fazendo o build, o aplicativo só é instalado depois do `sudo ninja install`. Ai então você vai poder desinstala-lo utilizando o `sudo ninja uninstall`

**Comment by btd1337** [comment]
@robertsanseries Ja havia instalado antes. Esses comandos que eu exibi foram todos pra tentar remover.

**Comment by robertsanseries** [comment]
@btd1337 então tranquilo! só reinstalar como o @naaando falou! ;)
